version: '3'

volumes:
  mysql_db:

services:
  app:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/html/
      - ./logs/apache/:/var/logs/apache2/
      - ./logs/app/:/var/www/logs/
    ports:
      - ${APP_PORT}:80
    env_file:
      - .env
    links:
      - mysql:mysql
    restart: always
    container_name: codeigniter_app

  mysql:
    image: mysql
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_db:/var/lib/mysql
      - ./logs/mysql/:/var/logs/mysql/
    env_file:
      - .env
    restart: always
    container_name: mysql_codeigniter
