version: '3'

services:
  app:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/html/
    ports:
      - ${APP_PORT}:80
    env_file:
      - .env
    restart: always
    container_name: codeigniter_app
